import type { INodeProperties } from 'n8n-workflow';

const show = (operation: string[]) => ({ show: { resource: ['artifact'], operation } });

export function projectLocator(operations: string[]): INodeProperties {
	return {
		displayName: 'Project',
		name: 'project',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		description: 'The project the artifact belongs to. Every tenant has a project with slug "default".',
		modes: [
			{ displayName: 'From List', name: 'list', type: 'list', typeOptions: { searchListMethod: 'getProjects', searchable: true } },
			{ displayName: 'Slug', name: 'slug', type: 'string', placeholder: 'e.g. default' },
			{ displayName: 'ID', name: 'id', type: 'string', placeholder: 'e.g. 0192a1b2-...' },
		],
		displayOptions: show(operations),
	};
}

export const artifactOperations: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: { show: { resource: ['artifact'] } },
	default: 'upload',
	options: [
		{ name: 'Delete', value: 'delete', action: 'Delete an artifact', description: 'Delete an artifact and all its versions' },
		{ name: 'Download', value: 'download', action: 'Download an artifact', description: 'Fetch the file into a binary property' },
		{ name: 'Get', value: 'get', action: 'Get an artifact', description: 'Fetch one artifact by ID or external key' },
		{ name: 'Get Many', value: 'getMany', action: 'Get many artifacts', description: 'Search artifacts by description, tags and filters' },
		{ name: 'Get or Upload', value: 'getOrUpload', action: 'Get or upload an artifact by external key', description: 'Reuse the artifact stored under an external key, or upload this one if none is fresh enough' },
		{ name: 'Update', value: 'update', action: 'Update an artifact', description: 'Change title, description, tags, metadata or expiry' },
		{ name: 'Upload', value: 'upload', action: 'Upload an artifact', description: 'Store a file or text as a new artifact' },
	],
};

const contentFields: INodeProperties[] = [
	{
		displayName: 'Input Data Source',
		name: 'inputDataSource',
		type: 'options',
		default: 'binary',
		options: [
			{ name: 'Binary File', value: 'binary', description: 'Upload the file held in a binary property of the input item' },
			{ name: 'Text', value: 'text', description: 'Upload text or JSON typed here or built with an expression' },
		],
		displayOptions: show(['upload', 'getOrUpload']),
	},
	{
		displayName: 'Input Binary Field',
		name: 'binaryPropertyName',
		type: 'string',
		default: 'data',
		required: true,
		description: 'Name of the binary property that holds the file',
		displayOptions: { show: { resource: ['artifact'], operation: ['upload', 'getOrUpload'], inputDataSource: ['binary'] } },
	},
	{
		displayName: 'Content',
		name: 'content',
		type: 'string',
		typeOptions: { rows: 4 },
		default: '',
		required: true,
		description: 'The text to store, built with an expression if needed',
		displayOptions: { show: { resource: ['artifact'], operation: ['upload', 'getOrUpload'], inputDataSource: ['text'] } },
	},
	{
		displayName: 'File Name',
		name: 'filename',
		type: 'string',
		default: '',
		placeholder: 'e.g. report.json',
		description: 'Stored file name. Defaults to the binary file name, or a generated name for text.',
		displayOptions: show(['upload', 'getOrUpload']),
	},
	{
		displayName: 'Content Type',
		name: 'contentType',
		type: 'string',
		default: '',
		placeholder: 'e.g. application/json',
		description: 'MIME type. Defaults to the binary file type, or text/plain for text.',
		displayOptions: show(['upload', 'getOrUpload']),
	},
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		default: '',
		placeholder: 'e.g. Q3 supplier emissions',
		description: 'What the artifact is. Searched by other agents. Defaults to the file name',
		displayOptions: show(['upload', 'getOrUpload']),
	},
];

const uploadOptions: INodeProperties = {
	displayName: 'Options',
	name: 'uploadOptions',
	type: 'collection',
	placeholder: 'Add option',
	default: {},
	displayOptions: show(['upload', 'getOrUpload']),
	options: [
		{ displayName: 'Description', name: 'description', type: 'string', typeOptions: { rows: 3 }, default: '', description: 'Longer description; searched semantically' },
		{ displayName: 'Expires In (Hours)', name: 'expiresInHours', type: 'number', default: 0, description: 'Delete the artifact automatically after this many hours. 0 keeps it.', displayOptions: { show: { '/operation': ['upload'] } } },
		{ displayName: 'External Key', name: 'externalKey', type: 'string', default: '', description: 'Your own unique key for this artifact within the project, e.g. a source URL or a hash', displayOptions: { show: { '/operation': ['upload'] } } },
		{ displayName: 'Metadata (JSON)', name: 'metadata', type: 'json', default: '{}', description: 'Structured metadata, searchable by filters' },
		{ displayName: 'Tags', name: 'tags', type: 'string', default: '', placeholder: 'e.g. finance, q3, csv', description: 'Comma-separated tags' },
	],
};

export const artifactFields: INodeProperties[] = [
	projectLocator(['upload', 'getOrUpload', 'getMany']),
	{
		displayName: 'External Key',
		name: 'externalKey',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'e.g. weather:2026-09-23:vilnius',
		description: 'The key that identifies this result. If an artifact with this key exists and is fresh enough, it is returned instead of uploading.',
		displayOptions: show(['getOrUpload']),
	},
	{
		displayName: 'Max Age (Seconds)',
		name: 'maxAgeSeconds',
		type: 'number',
		default: 0,
		description: 'Reuse the stored artifact only if it is younger than this. 0 accepts any age.',
		displayOptions: show(['getOrUpload']),
	},
	...contentFields,
	uploadOptions,
	{
		displayName: 'Lookup',
		name: 'lookup',
		type: 'options',
		default: 'id',
		options: [
			{ name: 'By External Key', value: 'externalKey' },
			{ name: 'By ID', value: 'id' },
		],
		displayOptions: show(['get']),
	},
	{
		displayName: 'Artifact ID',
		name: 'artifactId',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'e.g. 0192a1b2-3c4d-7e5f-8a9b-0c1d2e3f4a5b',
		description: 'The artifact ID, e.g. from a previous Artefaktum node in this workflow',
		displayOptions: { show: { resource: ['artifact'], operation: ['download', 'update', 'delete'] } },
	},
	{
		displayName: 'Artifact ID',
		name: 'artifactId',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'e.g. 0192a1b2-3c4d-7e5f-8a9b-0c1d2e3f4a5b',
		description: 'The artifact ID, e.g. from a previous Artefaktum node in this workflow',
		displayOptions: { show: { resource: ['artifact'], operation: ['get'], lookup: ['id'] } },
	},
	{
		displayName: 'External Key',
		name: 'externalKey',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['artifact'], operation: ['get'], lookup: ['externalKey'] } },
	},
	{
		...projectLocator(['get']),
		displayOptions: { show: { resource: ['artifact'], operation: ['get'], lookup: ['externalKey'] } },
	},
	{
		displayName: 'Options',
		name: 'downloadOptions',
		type: 'collection',
		placeholder: 'Add option',
		default: {},
		displayOptions: show(['download']),
		options: [
			{ displayName: 'File Name', name: 'fileName', type: 'string', default: '', description: 'Override the file name on the binary property' },
			{ displayName: 'Put Output File in Field', name: 'binaryPropertyName', type: 'string', default: 'data', description: 'Name of the binary property to write the file to' },
			{ displayName: 'Verify Checksum', name: 'verifyChecksum', type: 'boolean', default: true, description: 'Whether to compare the downloaded bytes against the stored SHA-256' },
			{ displayName: 'Version ID', name: 'versionId', type: 'string', default: '', description: 'A specific version; defaults to the latest' },
		],
	},
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		default: '',
		placeholder: 'e.g. supplier emission factors 2026',
		description: 'What you are looking for, in words. Leave empty to list by filters only.',
		displayOptions: show(['getMany']),
	},
	{
		displayName: 'Search Mode',
		name: 'mode',
		type: 'options',
		default: 'hybrid',
		options: [
			{ name: 'Hybrid', value: 'hybrid', description: 'Keyword and meaning combined' },
			{ name: 'Semantic', value: 'semantic', description: 'By meaning' },
			{ name: 'Text', value: 'text', description: 'By keywords' },
		],
		displayOptions: show(['getMany']),
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: show(['getMany']),
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		typeOptions: { minValue: 1, maxValue: 100 },
		description: 'Max number of results to return',
		displayOptions: { show: { resource: ['artifact'], operation: ['getMany'], returnAll: [false] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of the raw data',
		displayOptions: show(['get', 'getMany']),
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add filter',
		default: {},
		displayOptions: show(['getMany']),
		options: [
			{ displayName: 'Content Types', name: 'contentTypes', type: 'string', default: '', placeholder: 'e.g. application/json, text/csv', description: 'Comma-separated MIME types' },
			{ displayName: 'Created After', name: 'createdAfter', type: 'dateTime', default: '' },
			{ displayName: 'Created Before', name: 'createdBefore', type: 'dateTime', default: '' },
			{ displayName: 'Include Superseded', name: 'includeSuperseded', type: 'boolean', default: false, description: 'Whether to include artifacts that a newer artifact supersedes' },
			{ displayName: 'Tags (All Of)', name: 'tags', type: 'string', default: '', placeholder: 'e.g. finance, q3', description: 'Comma-separated; every tag must match' },
		],
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add field',
		default: {},
		displayOptions: show(['update']),
		options: [
			{ displayName: 'Clear Expiry', name: 'clearExpiresAt', type: 'boolean', default: false, description: 'Whether to remove the expiry so the artifact is kept' },
			{ displayName: 'Description', name: 'description', type: 'string', typeOptions: { rows: 3 }, default: '' },
			{ displayName: 'Expires At', name: 'expiresAt', type: 'dateTime', default: '' },
			{ displayName: 'Metadata (JSON)', name: 'metadata', type: 'json', default: '{}' },
			{ displayName: 'Tags', name: 'tags', type: 'string', default: '', description: 'Comma-separated; replaces the existing tags' },
			{ displayName: 'Title', name: 'title', type: 'string', default: '' },
		],
	},
];
